name: Build plugin

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/build-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}',
              sha: context.sha
            })
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create release
        run: |
          gh release create build-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} -F .github/workflows/release-text.md
  build-linux:
    runs-on: ubuntu-latest
    needs: create-release
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Update rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Create bundle for VST3 and CLAP
        run: cargo xtask bundle saturator --release
      - name: Create zip from bundle
        run: |
          cd target/bundled/
          zip -r saturator-plugin-linux.zip *
      - name: Upload artefact to release
        run: |
          gh release upload build-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} target/bundled/saturator-plugin-linux.zip

  build-windows:
    runs-on: windows-latest
    needs: create-release
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Update rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Create bundle for VST3 and CLAP
        run: cargo xtask bundle saturator --release
      - name: Create zip from bundle
        run: |
          cd target/bundled/
          7z a saturator-plugin-win.zip *
      - name: Upload artefact to release
        run: |
          gh release upload build-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} target/bundled/saturator-plugin-win.zip

  build-mac:
    runs-on: macos-latest
    needs: create-release
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Update rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Create bundle for VST3 and CLAP
        run: cargo xtask bundle saturator --release
      - name: Create zip from bundle
        run: |
          cd target/bundled/
          zip -r saturator-plugin-mac.zip *
      - name: Upload artefact to release
        run: |
          gh release upload build-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} target/bundled/saturator-plugin-mac.zip